[db_server]
89.169.146.167 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/yc_key ansible_host=89.169.146.167

[1c_server]
51.250.10.103 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/yc_key ansible_host=51.250.10.103
111.88.245.153 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/yc_key ansible_host=111.88.245.153

[all:vars]
ansible_python_interpreter=/usr/bin/python3
