[db_server]
89.169.143.97 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/yc_key ansible_host=89.169.143.97

[1c_server]
51.250.8.103 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/yc_key ansible_host=51.250.8.103

[all:vars]
ansible_python_interpreter=/usr/bin/python3
