name: Deploy 1C Cluster

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy local tfstate
        run: cp -f /root/VKR_IaC_1C/terraform/terraform.tfstate terraform/terraform.tfstate

      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: terraform
        env:
          TF_VAR_cloud_id: ${{ secrets.YC_CLOUD_ID }}
          TF_VAR_folder_id: ${{ secrets.YC_FOLDER_ID }}

      - name: Wait for servers
        run: sleep 60

      - name: Run Ansible
        run: ansible-playbook -i inventory.ini site.yml
        working-directory: ansible
        env:
          ANSIBLE_HOST_KEY_CHECKING: False
